version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: s2001
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  loki:
    image: grafana/loki:main
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    ports:
      - '3100:3100'